#!/usr/bin/env python3
"""
View Phase 1 Visualizations
Simple web server to view the generated HTML reports
"""

import http.server
import socketserver
import webbrowser
import os
import sys
from threading import Timer

def find_html_reports():
    """Find all HTML reports in the visualization directory"""
    viz_dir = "results/phase1_visualization"
    if not os.path.exists(viz_dir):
        return []
    
    html_files = []
    for file in os.listdir(viz_dir):
        if file.endswith('.html'):
            html_files.append(os.path.join(viz_dir, file))
    
    return html_files

def create_index_page():
    """Create an index page linking to all reports"""
    viz_dir = "results/phase1_visualization"
    if not os.path.exists(viz_dir):
        return None
    
    html_files = [f for f in os.listdir(viz_dir) if f.endswith('.html')]
    
    if not html_files:
        return None
    
    index_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase 1 Visualization Reports</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            text-align: center;
            border-bottom: 3px solid #3498db;
            padding-bottom: 15px;
        }
        .report-list {
            list-style: none;
            padding: 0;
        }
        .report-list li {
            margin: 15px 0;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #3498db;
        }
        .report-list a {
            color: #2c3e50;
            text-decoration: none;
            font-weight: bold;
            font-size: 18px;
        }
        .report-list a:hover {
            color: #3498db;
        }
        .description {
            color: #666;
            margin-top: 5px;
            font-size: 14px;
        }
        .info-box {
            background-color: #d4edda;
            border: 1px solid #c3e6cb;
            padding: 15px;
            border-radius: 6px;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 Phase 1 Visualization Reports</h1>
        
        <div class="info-box">
            <h3>📋 About Phase 1 Visualization</h3>
            <p>Phase 1 focuses on geometric correction of QR patterns:</p>
            <ul>
                <li>🎯 <strong>Fourth Corner Detection</strong> - Calculate missing corner from 3 finder patterns</li>
                <li>🔄 <strong>Perspective Correction</strong> - Transform skewed patterns to rectangular view</li>
                <li>📊 <strong>Flexible Ratios</strong> - Support for rectangular patterns (not just square)</li>
                <li>🔧 <strong>Geometric Validation</strong> - Proper corner ordering and dimensions</li>
            </ul>
        </div>
        
        <h2>📄 Available Reports:</h2>
        <ul class="report-list">"""
    
    for html_file in sorted(html_files):
        file_base = html_file.replace('_phase1_report.html', '').replace('.html', '')
        index_content += f"""
            <li>
                <a href="{html_file}">📊 {file_base}</a>
                <div class="description">Phase 1 geometric correction analysis and visualization</div>
            </li>"""
    
    index_content += """
        </ul>
        
        <div style="text-align: center; margin-top: 30px; color: #666;">
            <p>🎨 Generated by Phase 1 Visualizer | QR Data Reader System</p>
            <p>Use visualization tools to analyze geometric correction processes</p>
        </div>
    </div>
</body>
</html>"""
    
    index_path = os.path.join(viz_dir, "index.html")
    with open(index_path, 'w') as f:
        f.write(index_content)
    
    return index_path

def open_browser(url):
    """Open the browser after a short delay"""
    webbrowser.open(url)

def start_server(port=8000):
    """Start a simple HTTP server to view the visualizations"""
    
    # Check if visualization directory exists
    viz_dir = "results/phase1_visualization"
    if not os.path.exists(viz_dir):
        print("❌ No visualization directory found.")
        print("   Run the Phase 1 visualization first:")
        print("   python3 test_phase1_visualization.py")
        return
    
    # Check for HTML files
    html_files = find_html_reports()
    if not html_files:
        print("❌ No HTML reports found.")
        print("   Run the Phase 1 visualization first:")
        print("   python3 test_phase1_visualization.py")
        return
    
    print(f"📄 Found {len(html_files)} HTML report(s)")
    
    # Create index page
    index_path = create_index_page()
    
    # Change to the visualization directory
    original_dir = os.getcwd()
    os.chdir(viz_dir)
    
    try:
        # Start the server
        Handler = http.server.SimpleHTTPRequestHandler
        with socketserver.TCPServer(("", port), Handler) as httpd:
            print(f"🌐 Starting web server at http://localhost:{port}")
            print(f"📊 Serving Phase 1 visualizations...")
            print(f"🎯 Open your browser to: http://localhost:{port}")
            
            # Open browser after 1 second
            Timer(1.0, open_browser, [f"http://localhost:{port}"]).start()
            
            print("\nPress Ctrl+C to stop the server")
            httpd.serve_forever()
            
    except KeyboardInterrupt:
        print("\n🛑 Server stopped")
    except OSError as e:
        if "Address already in use" in str(e):
            print(f"❌ Port {port} is already in use. Try a different port:")
            print(f"   python3 view_phase1.py {port + 1}")
        else:
            print(f"❌ Error starting server: {e}")
    finally:
        os.chdir(original_dir)

if __name__ == "__main__":
    port = 8000
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            print("Invalid port number. Using default port 8000.")
    
    start_server(port)
